(* RangerLang EBNF grammar rules *)



identifier          = letter, {letter | digit | "_"} 
                    ;

number              = digit, {digit} 
                    ;


(* Fundamental rules *)

character           = digit | letter | symbol 
                    ;

letter              = uppercase | lowercase 
                    ;

digit               = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" 
                    ;

whitespace          = ? whitespace characters ? 
                    ;

symbol              = " " | "'" | '"' | "!" | "@" | "#" | "$" | "%" | "^" | "&"
                    | "*" | "(" | ")" | "_" | "-" | "+" | "=" | ";" | ":" | ","
                    | "." | "<" | ">" | "/" | "?" | "[" | "{" | "]" | "}" | "|"
                    | "\" | "~" | "`" 
                    ;

uppercase           = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
                    | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
                    | "U" | "V" | "W" | "X" | "Y" | "Z" 
                    ;

lowercase           = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" 
                    | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" 
                    | "u" | "v" | "w" | "x" | "y" | "z" 
                    ;


(* ENBF Cheatsheet - https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form

   =      - definition          [...]  - optional
   ,      - concatenation       {...}  - repetition; ZERO or more
   ;      - termination         (...)  - grouping
   |      - alternation         ?...?  - special sequence    
   "..."  - terminal string     '...'  - terminal string
   -      - exception
*)
